apiVersion: apps/v1
kind: Deployment
metadata:
  name: gfa-anagrafiche-deployment
  labels:
    microservice: gfa-anagrafiche
spec:
  replicas: 1
  selector:
    matchLabels:
      microservice: gfa-anagrafiche
  template:
    metadata:
      labels:
        microservice: gfa-anagrafiche
    spec:
      containers:
      - name: gfa-anagrafiche
        image: gfa-anagrafiche
        imagePullPolicy: Never
        ports:
        - containerPort: {{ default 8080 .Values.defaultSpringBootPort }}
        env:
        - name: SECRET_USER
          valueFrom:
            secretKeyRef:
              name: db-security
              key: db.username
        - name: SECRET_PSW
          valueFrom:
            secretKeyRef:
              name: db-security
              key: db.password
---
apiVersion: v1
kind: Service
metadata:
  name: gfa-anagrafiche
spec:
  selector:
    microservice: gfa-anagrafiche
  ports:
  - protocol: "TCP"
    port: {{ default 8080 .Values.microservicesPort }}
    targetPort: {{ default 8080 .Values.defaultSpringBootPort }}
