apiVersion: v1
kind: ConfigMap
metadata:
  name: gfa-gateway
data:
  application.yaml: |-
    server:
      port: {{ default 8080 .Values.defaultSpringBootPort }}
    uri:
      test: http://gfa-be-service
