apiVersion: v1
kind: ConfigMap
metadata:
  name: gfa-gateway
data:
  application.yaml: |-
    server:
      port: {{ default 8080 .Values.defaultSpringBootPort }}
    uri:
      anagrafiche: http://gfa-anagrafiche:{{ default 8080 .Values.microservicesPort }}
      file-manager: http://gfa-file-manager:{{ default 8080 .Values.microservicesPort }}
