apiVersion: v1
kind: ConfigMap
metadata:
  name: gfa-file-manager
data:
  application.yaml: |-
    server:
      port: {{ default 8080 .Values.defaultSpringBootPort }}

    spring:
      datasource:
        url: jdbc:oracle:thin:@db-service:{{ default 1521 .Values.db.port }}/pdb1.bip.lan
