apiVersion: v1
kind: ConfigMap
metadata:
  name: gfa-gestionale
data:
  application.yaml: |-
    server:
      port: {{ default 8080 .Values.defaultSpringBootPort }}
    gateway:
      host: http://gfa-gateway:{{ default 8080 .Values.microservicesPort }}
    spring:
      redis:
        host: gfa-redis-master
        port: 6379
        password: {{ .Values.global.redis.password }}

    # spring:
    #   datasource:
    #     url: jdbc:oracle:thin:@db-service:{{ default 1521 .Values.db.port }}/pdb1.bip.lan