kind: Service
apiVersion: v1
metadata:
  name: db-service
spec:
  clusterIP: None
  ports:
  - port: {{ default 1521 .Values.db.port }}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: db-service
subsets:
  - addresses:
        - ip: {{ default "127.0.0.1" .Values.db.ip }}
    ports:
      - port: {{ default 1521 .Values.db.port }}
        name: db-service
