apiVersion: v1
kind: ConfigMap
metadata:
  name: gfa-anagrafiche
data:
  application.yaml: |-
    server:
      port: {{ default 8080 .Values.defaultSpringBootPort }}
    db:
      host: db-service
      port: {{ default 1521 .Values.db.port }}
