apiVersion: v1
kind: ConfigMap
metadata:
  name: gfa-file-manager
data:
  application.yaml: |-
    server:
      port: {{ default 8080 .Values.defaultSpringBootPort }}

    spring:
      datasource:
        url: {{ .Values.db.url }}
