apiVersion: v1
kind: ConfigMap
metadata:
  name: gfa-gestionale
data:
  application.yaml: |-
    server:
      port: {{ default 8080 .Values.defaultSpringBootPort }}
    gateway:
      host: http://gfa-gateway-service
