apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gfa-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: gfa.com
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gfa-gestionale-service
            port:
              number: {{ default 8080 .Values.defaultSpringBootPort }}
